---
- name: Test NetBox API Connection
  hosts: all
  gather_facts: no
  tasks:
    - name: Get Server IP manually
      ansible.builtin.shell: "ip route get 1.1.1.1 | awk '{print $7}'"
      register: server_ip_result

    - name: Get NetBox Status from API
      ansible.builtin.uri:
        url: "http://10.201.6.37:8000/api/status/"
        method: GET
        status_code: 200
        validate_certs: false
        headers:
          Authorization: "Bearer nbt_iPhxAmW1x8rK.zA2u8f3d1c6STZAtMubFhGe39aOnAsIkcKIlDZ4W"
          Content-Type: "application/json"
          Accept: "application/json; indent=4"
      register: netbox_status

    - name: Display NetBox and Server Information
      debug:
        msg:
          - "Successfully connected to NetBox!"
          - "NetBox Version: {{ netbox_status.json['netbox-version'] }}"
          - "Server IP Address: {{ server_ip_result.stdout | trim }}"
